AllCops:
  Exclude:
    - '**/metadata.rb'
    - 'Vagrantfile'

ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false

CollectionMethods:
  Enabled: false
LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 25

